apiVersion: apps/v1
kind: Deployment
metadata:
  name: gauravrehanhelloworld
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gauravrehanhelloworld
  template:
    metadata:
      labels:
        app: gauravrehanhelloworld
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
        - name: gauravrehanhelloworld
          image: gaurehaacrrepository.azurecr.io/gauravhelloworld:0.0.1-SNAPSHOT
          ports:
            - containerPort: 8081

---
apiVersion: v1
kind: Service
metadata:
  name: gauravrehanhelloworld
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8081
      protocol: TCP
  selector:
    app: gauravrehanhelloworld
